name: Boruc.WeddingWeb.PullRequest-$(FullSemVer)

pr:
  branches:
    include:
      - feature/*
      - bugfix/*
      - hotfix/*
  paths:
    include:
    - src
  drafts: false

stages:
- stage: Build
  displayName: Wedding.Web.Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      - name: projectPath
        value: ''
      - name: buildConfiguration
        value: 'Release'

    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
      displayName: Use Dot Net.

    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      inputs:
        useConfigFile: true
        configFilePath: './pipelines/GitVersion/GitVersion.yml'
        additionalArguments: '/updateprojectfiles'

- stage: CreateTestEnvironment
  dependsOn: [] #[Build]
  # condition: succeeded()
  displayName: Wedding.Web.TerraformApply
  jobs:
  - deployment: Test
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'wedding-web-test'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
